### PR TITLE
lorge refactor

### PR DESCRIPTION
**Pull request by rhelmot**
make it work with ida 7 and clean everything else up

### CODE REVIEW

**Comment by rhelmot** [comment]
eric asked me to

**Comment by zardus** [comment]
dam

**Comment by rhelmot** [comment]
plus I think we might be able to shove a tiny shim layer between python 2 (running idalink) and python 3 (running angr) in order to make the ida backend work until idapython switches to python 3

**Comment by zardus** [comment]
oh no

**Pull request merged**
